// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reinstructible.Server.DL;

#nullable disable

namespace Reinstructible.Server.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20251211222424_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Reinstructible.Server.DBModels.Color", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_trans")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("rgb")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.Element", b =>
                {
                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("color_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("part_img_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("part_num_id")
                        .HasColumnType("TEXT");

                    b.HasKey("element_id");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.Inventory", b =>
                {
                    b.Property<string>("set_num")
                        .HasColumnType("TEXT");

                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_spare")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("set_num", "element_id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.LegoSet", b =>
                {
                    b.Property<string>("set_num")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("num_parts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("set_img_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("set_url")
                        .HasColumnType("TEXT");

                    b.Property<int>("theme_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("set_num");

                    b.ToTable("LegoSets");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.Part", b =>
                {
                    b.Property<string>("part_num")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("part_cat_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("part_url")
                        .HasColumnType("TEXT");

                    b.Property<int>("year_from")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year_to")
                        .HasColumnType("INTEGER");

                    b.HasKey("part_num");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.PartCategory", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("part_count")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("PartCategorys");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.Storage", b =>
                {
                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("bin")
                        .HasColumnType("TEXT");

                    b.Property<string>("drawer")
                        .HasColumnType("TEXT");

                    b.HasKey("element_id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.SubInventory", b =>
                {
                    b.Property<string>("set_num")
                        .HasColumnType("TEXT");

                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("page")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("step")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subBuildName")
                        .HasColumnType("TEXT");

                    b.HasKey("set_num", "element_id");

                    b.ToTable("SubInventories");
                });

            modelBuilder.Entity("Reinstructible.Server.DBModels.Theme", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("parent_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Themes");
                });
#pragma warning restore 612, 618
        }
    }
}
