// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reinstructible.Server.DL;

#nullable disable

namespace Reinstructible.Server.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class sqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Reinstructible.Server.Models.Color", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_trans")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("rgb")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Element", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("colorid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("inv_part_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_spare")
                        .HasColumnType("INTEGER");

                    b.Property<int>("num_sets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("part_num")
                        .HasColumnType("TEXT");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("set_num")
                        .HasColumnType("TEXT");

                    b.Property<int>("storage_locationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("colorid");

                    b.HasIndex("part_num");

                    b.HasIndex("storage_locationId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.LegoSet", b =>
                {
                    b.Property<string>("set_num")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("last_modified_dt")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("num_parts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("set_img_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("set_url")
                        .HasColumnType("TEXT");

                    b.Property<int>("theme_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("set_num");

                    b.ToTable("LegoSets");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Part", b =>
                {
                    b.Property<string>("part_num")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("alternates")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("molds")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("part_cat_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("part_img_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("part_url")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("prints")
                        .HasColumnType("TEXT");

                    b.Property<int>("year_from")
                        .HasColumnType("INTEGER");

                    b.Property<int>("year_to")
                        .HasColumnType("INTEGER");

                    b.HasKey("part_num");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.PartCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("part_count")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("PartCategorys");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Drawer")
                        .HasColumnType("TEXT");

                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.SubInventory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Elementid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("element_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("page")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("set_num")
                        .HasColumnType("TEXT");

                    b.Property<int>("step")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subBuildName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Elementid");

                    b.ToTable("SubInventories");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Theme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegoSetset_num")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("parent_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("LegoSetset_num");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Element", b =>
                {
                    b.HasOne("Reinstructible.Server.Models.Color", "color")
                        .WithMany()
                        .HasForeignKey("colorid");

                    b.HasOne("Reinstructible.Server.Models.Part", "part")
                        .WithMany()
                        .HasForeignKey("part_num");

                    b.HasOne("Reinstructible.Server.Models.Storage", "storage_location")
                        .WithMany()
                        .HasForeignKey("storage_locationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("color");

                    b.Navigation("part");

                    b.Navigation("storage_location");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.SubInventory", b =>
                {
                    b.HasOne("Reinstructible.Server.Models.Element", null)
                        .WithMany("sub_inventory")
                        .HasForeignKey("Elementid");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Theme", b =>
                {
                    b.HasOne("Reinstructible.Server.Models.LegoSet", null)
                        .WithMany("theme")
                        .HasForeignKey("LegoSetset_num");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.Element", b =>
                {
                    b.Navigation("sub_inventory");
                });

            modelBuilder.Entity("Reinstructible.Server.Models.LegoSet", b =>
                {
                    b.Navigation("theme");
                });
#pragma warning restore 612, 618
        }
    }
}
